[package]
name = "scattering-solver-rust-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
faer = "0.20.2"
scattering-problems = { git = "https://github.com/Wleter/quantum-rs" }
scattering-solver = { git = "https://github.com/Wleter/quantum-rs" }