[package]
name = "scattering-solver-rust-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
quantum = { git = "https://github.com/Wleter/quantum-rs", features = ["spins"]}
clebsch-gordan = { git = "https://github.com/Wleter/clebsch-gordan", branch = "master" }